<?xml version="1.0"?>
<package format="3">
  <name>tomato_picker_motion</name>
  <version>0.1.0</version>
  <description>MoveIt 2 based arm motion capability for Tomato-Picker</description>
  <maintainer email="kaerei@foxmail.com">Kaede Rei</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>geometry_msgs</depend>
  <depend>moveit_msgs</depend>
  <depend>moveit_ros_planning_interface</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>
  <depend>tomato_picker_interfaces</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
